version: '3.8'

services:
  # Serviço RabbitMQ
  rabbitmq:
    image: "rabbitmq:management"
    container_name: "rabbitmq"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "15672:15672"  # Porta para o console de administração
      - "5672:5672"    # Porta padrão para o RabbitMQ
    networks:
      - order-flow-network

  # Serviço SQL Server
  sqlserver:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: "sqlserver"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Passw0rd
    ports:
      - "1433:1433"  # Porta do SQL Server
    networks:
      - order-flow-network

  # Serviço Jaeger
  jaeger:
    image: "jaegertracing/all-in-one:1.38"
    container_name: "jaeger"
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    ports:
      - "5775:5775"  # Zipkin Thrift Port
      - "6831:6831/udp"  # Jaeger agent port
      - "6832:6832/udp"  # Jaeger agent port
      - "5778:5778"  # Jaeger UI
      - "16686:16686"  # Jaeger UI
      - "14250:14250"  # Jaeger GRPC Port
      - "14268:14268"  # Jaeger HTTP Port
    networks:
      - order-flow-network

  # Serviço para a API (seu projeto)
  api:
    build: .
    container_name: "ambev-orderflow-api"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DefaultConnection=Server=sqlserver;Database=OrderFlowDb;User=sa;Password=YourStrong!Passw0rd
      - RabbitMQ__Host=rabbitmq
      - RabbitMQ__Username=guest
      - RabbitMQ__Password=guest
      - Jaeger__AgentHost=jaeger
      - Jaeger__AgentPort=6831
    depends_on:
      - rabbitmq
      - sqlserver
      - jaeger
    ports:
      - "6000:80"  # Porta da API
    networks:
      - order-flow-network

networks:
  order-flow-network:
    driver: bridge
