<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="EntityFramework" Version="6.5.1" />
		<PackageReference Include="MediatR" Version="12.5.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.4" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Abstractions" Version="9.0.4" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.4">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="9.0.4" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.4" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.4">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="OpenTelemetry" Version="1.11.2" />
		<PackageReference Include="OpenTelemetry.Exporter.Jaeger" Version="1.5.1" />
		<PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.11.2" />
		<PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.11.1" />
		<PackageReference Include="OpenTelemetry.Instrumentation.Http" Version="1.11.1" />
		<PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Ambev.OrderFlow.Application\Ambev.OrderFlow.Application.csproj" />
		<ProjectReference Include="..\Ambev.OrderFlow.Infrastructure\Ambev.OrderFlow.Infrastructure.csproj" />
	</ItemGroup>

</Project>
